print('nume:') 
print('Terinte Livia')
print('adresa:')
print('Str.Vasile Alecsandri 6')
print('nr.de telefon:')
print('068278551')
print('data,locul nasterii:')
print('04.08.2004')
print('E-mail:')
print('terinte.livia@gmail.com')
print('nationalitate:')
print('moldoveanca')
print('studii:')
print('Institutia Publica Liceul Teoretic "Mihai Eminescu"')
print('hobby-uri:')
print('dansul,pianul,pictura,cititul,calatorii')